changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "🚀 New Features"
      labels:
        - feat
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - fix
        - bugfix
    - title: "⚡ Performance"
      labels:
        - perf
        - performance
    - title: "🔧 Improvements"
      labels:
        - refactor
        - improve
    - title: "✅ Tests"
      labels:
        - test
    - title: "📚 Documentation"
      labels:
        - docs
    - title: "🔨 Maintenance"
      labels:
        - chore
        - ci
